flags: {}
packages:
- hello
- hello-obj
- asteroids
- lambdacube-obj
extra-deps:
- lambdacube-compiler-0.6.0.1
- megaparsec-5.0.1
- lambdacube-gl-0.5.2.4
- wavefront-0.7.1
- MonadRandom-0.5.1
- GLFW-b-1.4.8.4
- bindings-GLFW-3.2.1.1
resolver: lts-6.25
